globalexperts/Source/globalexperts/globalexperts/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from trade_admin_auth.views import adminlogin
from trade_auth.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^global/',include("trade_auth.urls" ,namespace="trade_auth")),
    re_path(r'^tradeadmin/',include("trade_admin_auth.urls" ,namespace="trade_admin_auth")),
    re_path(r'^trademaster/',include("trade_master.urls" ,namespace="trade_master")),
    re_path(r'^token/',include("cryptotoken.urls" ,namespace="cryptotoken")),
    re_path(r'^support/',include("support.urls" ,namespace="support")),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    re_path('LELPMDfDsmez0ksi', adminlogin, name='adminlogin'),
    re_path('', home, name='home'),
]

globalexperts/Source/globalexperts/support/urls.py
from django.urls import include, path,re_path
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView
app_name = 'support'

loginurl='/W8n9cQU3MAh1mjhT/'

from . import views
from .views import AddSupportCategory,ListSupportCategory,UpdateSupportCategory
from .views import  ListSupportTicket,UpdateSupportTicket,DetailSupportticket,AddNewsletter,ListNewsletter,DetailNewsletter
from .views import ListSubscribeUserAdmin,DeleteSubscribeuser,AddSupportView
from django.views.decorators.csrf import csrf_exempt
urlpatterns = [

	 

	
	re_path(r'^updatesupportcategory/(?P<pk>[-\w]+)/$', login_required(UpdateSupportCategory.as_view(),login_url=loginurl), name='updatesupportcategory'),
	re_path(r'^supportcategorylist/$', login_required(ListSupportCategory.as_view(),login_url=loginurl), name='supportcategorylist'), 
	re_path(r'^addsupportcategory/$', login_required(AddSupportCategory.as_view(),login_url=loginurl), name='addsupportcategory'),
	
	re_path(r'^updatesupportticket/(?P<pk>[-\w]+)/$', login_required(UpdateSupportCategory.as_view(),login_url=loginurl), name='updatesupportticket'),
	re_path(r'^ticketsupportlist/$', login_required(ListSupportTicket.as_view(),login_url=loginurl), name='ticketsupportlist'), 
	re_path(r'^detail_supportticket/(?P<supportid>[-\w]+)/$', login_required(views.supportreply_view,login_url=loginurl), name='detail_supportticket'),

	re_path(r'^addnewsletter/$', login_required(AddNewsletter.as_view(),login_url=loginurl), name='addnewsletter'),
	re_path(r'^listnewsletter/$', login_required(ListNewsletter.as_view(),login_url=loginurl), name='listnewsletter'),
	re_path(r'^newsletterdetail/(?P<pk>[-\w]+)/$', login_required(DetailNewsletter.as_view(),login_url=loginurl), name='newsletterdetail'),

	re_path(r'^newsletter_add/$', login_required(views.newsletter_add,login_url=loginurl), name='newsletter_add'),
	re_path(r'^subscribedetail/(?P<pk>[-\w]+)/$', login_required(DeleteSubscribeuser.as_view(),login_url=loginurl), name='subscribedetail'),
	re_path(r'^subscribe_newsletter_add/$', views.subscribeuser, name='subscribe_newsletter_add'),

	re_path(r'^subscribelist/$', login_required(ListSubscribeUserAdmin.as_view(),login_url=loginurl), name='subscribelist'),
	re_path(r'^getuserlist_ajax', csrf_exempt(views.getuserlist_ajax), name='getuserlist_ajax'),

	re_path(r'^supportticket/$', login_required(AddSupportView.as_view()), name='supportticket'), 
	re_path(r'^tradeuser_supportticket/(?P<supportid>[-\w]+)/$', login_required(views.tradeusersupportreply_view), name='tradeuser_supportticket'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

globalexperts/Source/globalexperts/trade_master/urls.py
from django.urls import include, path,re_path
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
app_name = 'trade_master'

from . import views
from .views import UpdateCms_StaticContent,Liststaticcontent,DetailStaticcontent
from .views import UpdateCms_Content,Listcontent,Detailcontent
from .views import ListFaq,AddFaq,UpdateFaq,Detailfaq
from .views import Listcontactus,UpdateContactus,Detailcontactus
from .views import Listemailcontent,Updateemailcontenttemplate
from .views import AddTestimonial,ListTestimonial,UpdateTestimonial,DetailTestimonial
from .views import Blog_list,DetailBlog,UpdateBlogcontent,AddBlog,Marketingvideo_list
from .views import Updatevideo
loginurl='/LELPMDfDsmez0ksi/'

urlpatterns = [

	
	 re_path(r'^cms_page/(?P<pk>[-\w]+)/$', login_required(UpdateCms_StaticContent.as_view(),login_url=loginurl), name='cms_page'),
	 re_path(r'^cmspagelist/$', login_required(Liststaticcontent.as_view(),login_url=loginurl), name='cmspagelist'),
	 re_path(r'^cms_page_detail/(?P<pk>[-\w]+)/$', login_required(DetailStaticcontent.as_view(),login_url=loginurl), name='cms_page_detail'),

	 re_path(r'^cms_content/(?P<pk>[-\w]+)/$', login_required(UpdateCms_Content.as_view(),login_url=loginurl), name='cms_content'),
	 re_path(r'^cmspagecontentlist/$', login_required(Listcontent.as_view(),login_url=loginurl), name='cmspagecontentlist'),
	 re_path(r'^cms_page_contentdetail/(?P<pk>[-\w]+)/$', login_required(Detailcontent.as_view(),login_url=loginurl), name='cms_page_contentdetail'),

	 re_path(r'^updatetestimonial/(?P<pk>[-\w]+)/$', login_required(UpdateTestimonial.as_view(),login_url=loginurl), name='updatetestimonial'),
	 re_path(r'^testimoniallist/$', login_required(ListTestimonial.as_view(),login_url=loginurl), name='testimoniallist'),
	 re_path(r'^testimonialdetail/(?P<pk>[-\w]+)/$', login_required(DetailTestimonial.as_view(),login_url=loginurl), name='testimonialdetail'),
	 re_path(r'^addtestimonial/$', login_required(AddTestimonial.as_view(),login_url=loginurl), name='addtestimonial'),


	 re_path(r'^updatefaq/(?P<pk>[-\w]+)/$', login_required(UpdateFaq.as_view(),login_url=loginurl), name='updatefaq'),
	 re_path(r'^faqlist/$', login_required(ListFaq.as_view(),login_url=loginurl), name='faqlist'),
	 re_path(r'^addfaq/$', login_required(AddFaq.as_view(),login_url=loginurl), name='addfaq'),
	 re_path(r'^detail_faq/(?P<pk>[-\w]+)/$', login_required(Detailfaq.as_view(),login_url=loginurl), name='detail_faq'),

	 re_path(r'^contactus_update/(?P<pk>[-\w]+)/$', login_required(UpdateContactus.as_view(),login_url=loginurl), name='contactus_update'),
	 re_path(r'^contactlist/$', login_required(Listcontactus.as_view(),login_url=loginurl), name='contactlist'),
	 re_path(r'^contactusdetail/(?P<pk>[-\w]+)/$', login_required(Detailcontactus.as_view(),login_url=loginurl), name='contactusdetail'),

	 re_path(r'^updateemailcontent/(?P<pk>[-\w]+)/$', login_required(Updateemailcontenttemplate.as_view(),login_url=loginurl), name='updateemailcontent'),
	 re_path(r'^emailcontactlist/$', login_required(Listemailcontent.as_view(),login_url=loginurl), name='emailcontactlist'),

	re_path(r'^bloglist/$', login_required(Blog_list.as_view(),login_url=loginurl), name='bloglist'),
	re_path(r'^blog_detail/(?P<pk>[-\w]+)/$', login_required(DetailBlog.as_view(),login_url=loginurl), name='blog_detail'),
	re_path(r'^blog_page/(?P<pk>[-\w]+)/$', login_required(UpdateBlogcontent.as_view(),login_url=loginurl), name='blog_page'),
	re_path(r'^addblog/$', login_required(AddBlog.as_view(),login_url=loginurl), name='addblog'),


	re_path(r'^videolist/$', login_required(Marketingvideo_list.as_view(),login_url=loginurl), name='videolist'),
	re_path(r'^video_page/(?P<pk>[-\w]+)/$', login_required(Updatevideo.as_view(),login_url=loginurl), name='video_page'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

globalexperts/Source/globalexperts/trade_master/models.py
from django.db import models

from django.conf import settings


from datetime import date

from django.core.validators import RegexValidator
from auditable.models import Auditable

from django.urls import reverse
import os
from django.db.models import Q
from django.db.models import Count, Min, Sum, Avg ,F,DecimalField
from decimal import Decimal
import time

from ckeditor.fields import RichTextField


General_Status = (
					(0,'Active'),
					(1,'Inactive'),
					(2,'Cancel'),
	)
Content_type = (
	(0,'page'),
	(1,'content')

	)
Read_Status = (
	(0,'UnReply'),
	(1,'Replied')
	)

class Cms_StaticContent(Auditable):
	name = models.CharField(max_length=50,verbose_name='Name',blank=True,null=True)
	title = models.CharField(max_length=50,verbose_name='Title')
	content = RichTextField(help_text='Content',verbose_name='Content',blank=True,null=True)
	contenttype=models.IntegerField(choices=Content_type,default=0,verbose_name='Content')
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')

	def __int__self(self):
		return id
	class Meta:
		verbose_name='Cms_StaticContent'
		db_table='ax7XI2mneaLpb7Ud'


class Faq(Auditable):
	
	title = models.CharField(max_length=50,verbose_name='Question')
	content = models.TextField(help_text='Content',verbose_name='Content',blank=True,null=True)
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')

	def __int__self(self):
		return id
	class Meta:
		verbose_name='Faq'
		db_table='gAoTkpN4b2jBB6tV'


class Contactus(models.Model):

	phone1=models.CharField(max_length=13,verbose_name='Phone Number',blank=True,null=True)
	name =models.CharField(max_length=50,verbose_name='Name')
	email = models.CharField(max_length=50,verbose_name='Email')
	subject = models.CharField(max_length=50,verbose_name='Subject')
	message = models.TextField(help_text='Message',verbose_name='Message')
	reply = models.TextField(help_text='Message',verbose_name='Reply',blank=True,null=True)
	status =models.IntegerField(choices=General_Status,default=0,verbose_name='Status')
	read_status =models.IntegerField(choices=Read_Status,default=0,verbose_name='Read Status')
	created_on = models.DateTimeField(auto_now_add = True)
	modified_on = models.DateTimeField(auto_now=True)

	def __int__self(self):
		return id
	class Meta:
		verbose_name='Contactus'
		db_table='tg3bHbh1qpLYMIaS'


class EmailTemplate(Auditable):
	
	name = models.CharField(max_length=50,verbose_name='Name')
	Subject = models.CharField(max_length=300,verbose_name='Subject')
	content = RichTextField(help_text='Content',verbose_name='Content')
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')

	def __int__self(self):
		return id
	class Meta:
		verbose_name='EmailTemplate'
		db_table='rfkF0iB1AluS2NNQ'


class Testimonial(Auditable):
	name = models.CharField(max_length=50,verbose_name='Name')
	location = models.CharField(max_length=50,verbose_name='Position')
	content = RichTextField(help_text='Content',verbose_name='Content',blank=True,null=True)
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')
	photo=models.ImageField(upload_to='testimonialimages',verbose_name='Photo',blank=True,null=True)
	def __int__self(self):
		return id
	class Meta:
		verbose_name='Testimonial'
		db_table='DC1MIHelrUsOiies'


class Subscribeuser(models.Model):
	created_on = models.DateTimeField(auto_now_add = True)
	emailaddress = models.CharField(max_length=50)
	subscribe_status = models.CharField(max_length=50)
	class Meta:
		db_table = 'Z0EDN1feYgvqc7eB'


class Newsletter(models.Model):
	ty = (
		('All user','All user'),
		('Registered user','Registered user'),
		('Subscribed user','Subscribed user'),
	)
	Type = models.CharField(max_length=50,choices=ty,default="")
	email = models.CharField(max_length=50)
	subj = models.CharField(max_length=50)
	message = models.TextField()
	class Meta:
		db_table = 'TfFGdWoiaPvleABv'



class Blog(Auditable):
	blogtitle = models.CharField(max_length=100,verbose_name='Blog Name')
	blogimage = models.ImageField(upload_to='Blogimage',null=True,blank=True)
	blogcontent = RichTextField(help_text='Blogcontent',verbose_name='Blog Content',null=True,blank=True)
	blogsubject = models.TextField(help_text='Blogsubject',verbose_name='Blog subject',blank=True,null=True,default="")
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')

	def __int__self(self):
		return id
	class Meta:
		verbose_name = 'Blog'
		db_table = 'H5gqo7sKYMKJmelh'



class Marketingvideo(Auditable):
	videotitle = models.CharField(max_length=100,verbose_name='Video Title')
	videourl = models.CharField(max_length=100,blank=True,null=True)
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')

	def __int__self(self):
		return id
	class Meta:
		verbose_name = 'Marketingvideo'
		db_table = 'Ywv5RGoHxejMoUV'

globalexperts/Source/globalexperts/trade_master/forms.py
from django.forms import ModelForm
from django import forms


from django.forms import ModelChoiceField

from django.forms import widgets
from betterforms.multiform import MultiModelForm,MultiForm
from django.core.validators import MinValueValidator, MaxValueValidator
from collections import OrderedDict

from django.contrib.auth.models import User,Group
from company.models import Company,Company_Settings

from trade_master.models import Cms_StaticContent,Faq,Blog,Marketingvideo,Contactus,EmailTemplate,Testimonial




class TestimonialForm(forms.ModelForm):
    
    class Meta:
        model= Testimonial
        fields=['name', 'location','photo']
        exclude=['created_on','modified_on','status','content' ]

class ContentPageForm(forms.ModelForm):
    
    class Meta:
        model= Cms_StaticContent
        fields=['title', 'content']
        exclude=['name','contenttype','created_on','modified_on','status' ]


class Blogpageform(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['blogtitle','blogimage','blogcontent','blogsubject','status']
        exclude = ['created_on','modified_on']


class videoform(forms.ModelForm):
    class Meta:
        model = Marketingvideo
        fields = ['videotitle','videourl','status']
        exclude = ['created_on','modified_on']



class FaqForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={"rows":4, "cols":40}),required=True)
    class Meta:
        model= Faq
        fields=['title', 'content','status']
        exclude=['created_on','modified_on' ]

class ContactForm(forms.ModelForm):
    reply = forms.CharField(widget=forms.Textarea(attrs={"rows":4, "cols":40}),required=True)
    class Meta:
        model= Contactus
        fields=['reply',]
        exclude=['created_on','modified_on' ,'phone1','name','email','subject','message','read_status']

class EmailContentForm(forms.ModelForm):
    
    class Meta:
        model= EmailTemplate
        fields=['name', 'Subject','content']
        exclude=['created_on','modified_on' ]

globalexperts/Source/globalexperts/trade_master/templates/trade_master/blog_detail.html
{% extends 'default_theme/base/__base.html' %}
{% load staticfiles %} 

{% load form_custom %}


{% block Style_sheets %}
{{ subadmin_formset.media.css }}
{% endblock Style_sheets %}
{% load widget_tweaks %}

 {% block Content_Area %}
    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
     
   	 <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="box-title">{{ Title}}</h3>
          <div class="box-tools pull-right">
            {% comment %}
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
            {% endcomment %}
          </div>
        </div>
        {% if messages %}
     {% for message in messages %}
     <div class="alert {{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
         <!-- form start -->
         <form role="form" action="" method='post' enctype="multipart/form-data" novalidate ="novalidate">
             {% csrf_token %} 
             {{ form.media }}
        <!-- /.box-header -->
        <div class="box-body">
          <div class="row">
            <div class="col-md-6">
              
              <!-- /.form-group -->
                <div class="form-group">
                  <label >
                        Blog Title : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {{staticcontent_qs.blogtitle}}
                </div>
              <div class="form-group">
                  <label >
                        Blog Image : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {% if  staticcontent_qs.blogimage.url != None %}
                   <img src="{{staticcontent_qs.blogimage.url}}" width="100" height="100">
                    {% else %}
                    <img src="" alt="Blog Image">
                    {% endif %}
                </div>
              <div class="form-group">
                  <label >
                        Blog Subject : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {{staticcontent_qs.blogsubject}}
                </div>
                 <div class="form-group">
                  <label >
                        Blog Content : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {{staticcontent_qs.blogcontent}}
                </div>
                 <div class="form-group">
                  <label >
                        Blog Status : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                  {% if staticcontent_qs.status == 0 %}
                   Active
                  {% elif staticcontent_qs.status == 1 %}
                  InActive
                  {% else %}
                  Cancelled
                  {% endif %}
                </div>
                  
              <!-- /.form-group -->
            </div>
            <!-- /.col -->
            <div class="col-md-6">
             
            <!-- /.col -->
            </div>
          </div>
           <!-- /.second row -->
        <!-- /.box-body -->
         <div class="box-footer">

                 <a href="/trademaster/bloglist/" class="btn btn-primary">Back</a>
         </div>
          </form>
      </div>

    </section>
    <!-- /.content -->




 {% endblock Content_Area %}

 {% block Java_Scripts %}

 {% endblock %}

globalexperts/Source/globalexperts/trade_master/templates/trade_master/contactus_detail.html
{% extends 'default_theme/base/__base.html' %}
{% load staticfiles %} 

{% load form_custom %}


{% block Style_sheets %}
{{ subadmin_formset.media.css }}
{% endblock Style_sheets %}
{% load widget_tweaks %}

 {% block Content_Area %}
    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
     
   	 <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="box-title">{{ Title}}</h3>
          <div class="box-tools pull-right">
            {% comment %}
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
            {% endcomment %}
          </div>
        </div>
        {% if messages %}
     {% for message in messages %}
     <div class="alert {{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
         <!-- form start -->
         <form role="form" action="" method='post' enctype="multipart/form-data" novalidate ="novalidate">
             {% csrf_token %} 
             {{ form.media }}
        <!-- /.box-header -->
        <div class="box-body">
          <div class="row">
            <div class="col-md-6">
              
              <!-- /.form-group -->
                <div class="form-group">
                  <label >
                        Name : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {{staticcontent_qs.name}}
                </div>
              <div class="form-group">
                  <label >
                        Email : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {{staticcontent_qs.email}}
                </div>
                {% comment %}
               <div class="form-group">
                  <label >
                        Phone : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {{staticcontent_qs.phone1}}
                </div>
                {% endcomment %}
                 <div class="form-group">
                  <label >
                        Subject : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {{staticcontent_qs.subject}}
                </div>   
                  <div class="form-group">
                  <label >
                        Message : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {{staticcontent_qs.message}}
                </div>   
                 <div class="form-group">
                  <label >
                        Submitted On : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {{staticcontent_qs.created_on|date:"d-m-Y"}}
                </div>     
              <!-- /.form-group -->
            </div>
            <!-- /.col -->
            <div class="col-md-6">
              <div class="form-group">
                  <label >
                       Reply Status: 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {{ staticcontent_qs.get_read_status_display}}
                </div>   
                 <div class="form-group">
                  <label >
                       Reply On: 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                    {{staticcontent_qs.modified_on|date:"d-m-Y"}}
                </div>   
                 <div class="form-group">
                  <label >
                       Reply Message: 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                 {% if staticcontent_qs.reply %}
                    {{staticcontent_qs.reply}}
                 {% else %}
                 --
                 {% endif%}
                </div>    
           
            </div>
          </div>
           <!-- /.second row -->
        <!-- /.box-body -->
         <div class="box-footer">

                 <a href="/trademaster/contactlist/" class="btn btn-primary">Back</a>
         </div>
          </form>
      </div>

    </section>
    <!-- /.content -->




 {% endblock Content_Area %}

 {% block Java_Scripts %}

 {% endblock %}

globalexperts/Source/globalexperts/trade_master/templates/trade_master/menu.html
 <li>
          <a href="{% url 'trade_master:testimoniallist' %}" >
            <i class="fa fa-address-card"></i> <span>Manage Our Team</span>
          </a>
 </li>

<li class="{% if activecls == 'cmsstaticadmin'%} active {% endif %} treeview">
          <a href="#">
            <i class="fa fa-file"></i> <span>CMS Management</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
             <li><a href="{% url 'trade_master:cmspagecontentlist' %}"><i class="fa fa-circle-o"></i> CMS Home Content </a></li>
            <li><a href="{% url 'trade_master:cmspagelist' %}"><i class="fa fa-circle-o"></i> CMS Page </a></li>
            
          </ul>

        </li>

<li>
          <a href="{% url 'trade_master:bloglist' %}" >
            <i class="fa fa-address-card"></i> <span>Manage Blog</span>
          </a>
 </li>

 <li>
          <a href="{% url 'trade_master:videolist' %}" >
            <i class="fa fa-address-card"></i> <span>Manage Marketing Video</span>
          </a>
 </li>

<li>
          <a href="{% url 'trade_master:contactlist' %}" >
            <i class="fa fa-address-card"></i> <span>Manage Contact us</span>
          </a>
 </li>
<li>
  <a  href="{% url 'trade_master:faqlist' %}"><i class="fa fa-question-circle"></i> <span>Manage FAQ</span></a>
</li>
<li>
          <a href="{% url 'trade_master:emailcontactlist' %}">
            <i class="fa fa-envelope"></i> <span>Manage Email Template</span>
          </a>
 </li>



globalexperts/Source/globalexperts/trade_master/templates/trade_master/testimonialdetail.html
{% extends 'default_theme/base/__base.html' %}
{% load staticfiles %} 

{% load form_custom %}


{% block Style_sheets %}
{{ subadmin_formset.media.css }}
{% endblock Style_sheets %}
{% load widget_tweaks %}

 {% block Content_Area %}
    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
     
   	 <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="box-title">{{ Title}}</h3>
          <div class="box-tools pull-right">
            {% comment %}
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
            {% endcomment %}
          </div>
        </div>
        {% if messages %}
     {% for message in messages %}
     <div class="alert {{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
         <!-- form start -->
         <form role="form" action="" method='post' enctype="multipart/form-data" novalidate ="novalidate">
             {% csrf_token %} 
             {{ form.media }}
        <!-- /.box-header -->
        <div class="box-body">
          <div class="row">
            <div class="col-md-6">
              
              <!-- /.form-group -->
                <div class="form-group">
                  <label >
                        Name : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {{staticcontent_qs.name}}
                </div>
                <div class="form-group">
                  <label >
                        Position : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {{staticcontent_qs.location}}
                </div>
                 <div class="form-group">
                  <label >
                        Photo : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                 <img src="{{ staticcontent_qs.photo.url}}" >
                  
                </div>
                <div class="form-group">
                  <label >
                        Status : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {{staticcontent_qs.get_status_display}}
                </div>  
              <!-- /.form-group -->
            </div>
            <!-- /.col -->
            <div class="col-md-6">
             
            <!-- /.col -->
            </div>
          </div>
           <!-- /.second row -->
        <!-- /.box-body -->
         <div class="box-footer">

                 <a href="/trademaster/testimoniallist/" class="btn btn-primary">Back</a>
         </div>
          </form>
      </div>

    </section>
    <!-- /.content -->




 {% endblock Content_Area %}

 {% block Java_Scripts %}

 {% endblock %}