globalexperts/Source/globalexperts/cryptotoken/urls.py
from django.urls import include, path,re_path
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
app_name = 'cryptotoken'

from . import views
from .views import ListRoadMap,AddRoadMap,UpdateRoadMap,DetailRoadMap,ChangeTokenDetailView
from .views import ListCurrencyDetails,UpdateCurrencyDetail,DetailCurrencyDetail
from .views import AddTokenInformations,UpdateTokenInformations,ListTokenInformations,DetailToken
loginurl='/LELPMDfDsmez0ksi/'

urlpatterns = [

	re_path(r'^roadmapadd/$', login_required(AddRoadMap.as_view(),login_url=loginurl), name='roadmapadd'),
	re_path(r'^roadmaplist/$', login_required(ListRoadMap.as_view(),login_url=loginurl), name='roadmaplist'),
	re_path(r'^roademapdit/(?P<pk>[-\w]+)/$', login_required(UpdateRoadMap.as_view(),login_url=loginurl), name='roademapdit'),
	re_path(r'^roadmapdetail/(?P<pk>[-\w]+)/$', login_required(DetailRoadMap.as_view(),login_url=loginurl), name='roadmapdetail'),
	re_path(r'^tokensetting/(?P<pk>[-\w]+)/$', login_required(ChangeTokenDetailView.as_view(),login_url=loginurl), name='tokensetting'),
	re_path(r'^currencylist/$', login_required(ListCurrencyDetails.as_view(),login_url=loginurl), name='currencylist'),
	re_path(r'^currencyedit/(?P<pk>[-\w]+)/$', login_required(UpdateCurrencyDetail.as_view(),login_url=loginurl), name='currencyedit'),
	re_path(r'^currencydetail/(?P<pk>[-\w]+)/$', login_required(DetailCurrencyDetail.as_view(),login_url=loginurl), name='currencydetail'),

	re_path(r'^tokenadd/$', login_required(AddTokenInformations.as_view(),login_url=loginurl), name='tokenadd'),
	re_path(r'^tokenlist/$', login_required(ListTokenInformations.as_view(),login_url=loginurl), name='tokenlist'),
	re_path(r'^tokenedit/(?P<pk>[-\w]+)/$', login_required(UpdateTokenInformations.as_view(),login_url=loginurl), name='tokenedit'),
	re_path(r'^tokendetail/(?P<pk>[-\w]+)/$', login_required(DetailToken.as_view(),login_url=loginurl), name='tokendetail'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

globalexperts/Source/globalexperts/globalexperts/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from trade_admin_auth.views import adminlogin
from trade_auth.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^global/',include("trade_auth.urls" ,namespace="trade_auth")),
    re_path(r'^tradeadmin/',include("trade_admin_auth.urls" ,namespace="trade_admin_auth")),
    re_path(r'^trademaster/',include("trade_master.urls" ,namespace="trade_master")),
    re_path(r'^token/',include("cryptotoken.urls" ,namespace="cryptotoken")),
    re_path(r'^support/',include("support.urls" ,namespace="support")),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    re_path('LELPMDfDsmez0ksi', adminlogin, name='adminlogin'),
    re_path('', home, name='home'),
]

globalexperts/Source/globalexperts/support/urls.py
from django.urls import include, path,re_path
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView
app_name = 'support'

loginurl='/W8n9cQU3MAh1mjhT/'

from . import views
from .views import AddSupportCategory,ListSupportCategory,UpdateSupportCategory
from .views import  ListSupportTicket,UpdateSupportTicket,DetailSupportticket,AddNewsletter,ListNewsletter,DetailNewsletter
from .views import ListSubscribeUserAdmin,DeleteSubscribeuser,AddSupportView
from django.views.decorators.csrf import csrf_exempt
urlpatterns = [

	 

	
	re_path(r'^updatesupportcategory/(?P<pk>[-\w]+)/$', login_required(UpdateSupportCategory.as_view(),login_url=loginurl), name='updatesupportcategory'),
	re_path(r'^supportcategorylist/$', login_required(ListSupportCategory.as_view(),login_url=loginurl), name='supportcategorylist'), 
	re_path(r'^addsupportcategory/$', login_required(AddSupportCategory.as_view(),login_url=loginurl), name='addsupportcategory'),
	
	re_path(r'^updatesupportticket/(?P<pk>[-\w]+)/$', login_required(UpdateSupportCategory.as_view(),login_url=loginurl), name='updatesupportticket'),
	re_path(r'^ticketsupportlist/$', login_required(ListSupportTicket.as_view(),login_url=loginurl), name='ticketsupportlist'), 
	re_path(r'^detail_supportticket/(?P<supportid>[-\w]+)/$', login_required(views.supportreply_view,login_url=loginurl), name='detail_supportticket'),

	re_path(r'^addnewsletter/$', login_required(AddNewsletter.as_view(),login_url=loginurl), name='addnewsletter'),
	re_path(r'^listnewsletter/$', login_required(ListNewsletter.as_view(),login_url=loginurl), name='listnewsletter'),
	re_path(r'^newsletterdetail/(?P<pk>[-\w]+)/$', login_required(DetailNewsletter.as_view(),login_url=loginurl), name='newsletterdetail'),

	re_path(r'^newsletter_add/$', login_required(views.newsletter_add,login_url=loginurl), name='newsletter_add'),
	re_path(r'^subscribedetail/(?P<pk>[-\w]+)/$', login_required(DeleteSubscribeuser.as_view(),login_url=loginurl), name='subscribedetail'),
	re_path(r'^subscribe_newsletter_add/$', views.subscribeuser, name='subscribe_newsletter_add'),

	re_path(r'^subscribelist/$', login_required(ListSubscribeUserAdmin.as_view(),login_url=loginurl), name='subscribelist'),
	re_path(r'^getuserlist_ajax', csrf_exempt(views.getuserlist_ajax), name='getuserlist_ajax'),

	re_path(r'^supportticket/$', login_required(AddSupportView.as_view()), name='supportticket'), 
	re_path(r'^tradeuser_supportticket/(?P<supportid>[-\w]+)/$', login_required(views.tradeusersupportreply_view), name='tradeuser_supportticket'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

globalexperts/Source/globalexperts/cryptotoken/models.py
from django.db import models

from django.conf import settings


from datetime import date

from django.core.validators import RegexValidator
from auditable.models import Auditable

from django.urls import reverse
import os
from django.db.models import Q
from django.db.models import Count, Min, Sum, Avg ,F,DecimalField
from decimal import Decimal
import time
import uuid
from ckeditor.fields import RichTextField
from django.utils import timezone
General_Status = (
					(0,'Active'),
					(1,'Inactive'),
					(2,'Cancel'),
	)
Liquidity_Lock = (
					(0,'UnLock'),
					(1,'Lock')
	)
class TokenDetails(Auditable):
	name = models.CharField(max_length=50,verbose_name='Name')
	symbol = models.CharField(max_length=50,verbose_name='Symbol')
	platform= models.CharField(max_length=50,verbose_name='Platform')
	supply=models.CharField(max_length=50,verbose_name='Total Supply',blank=True,null=True)
	teamwallet=models.CharField(max_length=50,verbose_name='Total Wallet',blank=True,null=True)
	presupply =models.CharField(max_length=50,verbose_name='Pre-Sale Supply ',blank=True,null=True)
	liquidtypool=models.CharField(max_length=50,verbose_name='Liquidity Pool',blank=True,null=True)
	token_burn =models.CharField(max_length=50,verbose_name='Token Burn',blank=True,null=True)
	presaleprice =models.CharField(max_length=50,verbose_name='Dx Sale Pre-Sale Price',blank=True,null=True)
	pancakeswap=models.CharField(max_length=50,verbose_name='PancakeSwap Price',blank=True,null=True)
	liquidity_lock = models.IntegerField(choices=General_Status,default=0,verbose_name='Status')
	content = models.TextField(help_text='Content',verbose_name='Content',blank=True,null=True)
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')
	def __str__(self):
		return "%s" % self.name

	class Meta:
		db_table='dT55INJGxASL7ISW'
		ordering = ['id']
		verbose_name = "TokenDetails"
		verbose_name_plural ="TokenDetails"
		indexes = [
			models.Index(fields=['name','symbol','status'])
		]


class RoadMap(Auditable):
	title = models.CharField(max_length=50,verbose_name='Title')
	years = models.CharField(max_length=50,verbose_name='Years')
	content = models.TextField(help_text='Content',verbose_name='Content',blank=True,null=True)
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')
	def __str__(self):
		return "%s" % self.title

	class Meta:
		db_table='cPWZ2sKnkhxQPL4c'
		ordering = ['id']
		verbose_name = "RoadMap"
		verbose_name_plural ="RoadMaps"
		indexes = [
			models.Index(fields=['title','years','status'])
		]


class CurrencyDetails(Auditable):
	name = models.CharField(max_length=50,verbose_name='Name')
	symbol = models.CharField(max_length=50,verbose_name='Symbol')
	platform= models.CharField(max_length=50,verbose_name='Platform')
	supply=models.CharField(max_length=50,verbose_name='Total Supply')
	reward_distributed =models.DecimalField(max_digits=8,decimal_places=2,verbose_name='Distributor Holder (%)',default=0.0)
	charity =models.DecimalField(max_digits=8,decimal_places=2,verbose_name='Charity Wallet (%)',default=0.0)
	marketing =models.DecimalField(max_digits=8,decimal_places=2,verbose_name='Marketing Wallet (%)',default=0.0)
	teamwallet=models.DecimalField(max_digits=8,decimal_places=2,verbose_name='Team Wallet (%)',default=0.0)
	teamwallet_duration= models.IntegerField(verbose_name='Team Wallet Duration',default=0)
	presupply =models.DecimalField(max_digits=8,decimal_places=2,verbose_name='Pre-Sale Supply (%) (DxSale)',default=0.0)
	liquidtypool=models.DecimalField(max_digits=8,decimal_places=2,verbose_name='Liquidity Pool (%) (PancakeSwap)',default=0.0)
	presaleprice =models.CharField(max_length=50,verbose_name='Dx Sale Pre-Sale Price',blank=True,null=True)
	pancakeswap=models.CharField(max_length=50,verbose_name='PancakeSwap Price',blank=True,null=True)
	token_burn =models.DecimalField(max_digits=8,decimal_places=2,verbose_name='Token Burn (%)',default=0.0)
	blackholeaddress = models.CharField(max_length=100,verbose_name='Hole Address',blank=True,null=True)
	liquiditylock = models.IntegerField(choices=Liquidity_Lock,default=0,verbose_name='Liquidity Lock')
	content = models.TextField(help_text='Content',verbose_name='Content',blank=True,null=True)
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')
	attachments = models.FileField(upload_to='currencywhitepaper',verbose_name='WhitePaper',blank=True,null=True)
	timerdate = models.DateTimeField(default=timezone.now,blank=True,null=True,verbose_name='Date')
	def __str__(self):
		return "%s" % self.name

	class Meta:
		db_table='fVqNkSDHT1M6Z0D6'
		ordering = ['id']
		verbose_name = "CurrencyDetails"
		verbose_name_plural ="CurrencyDetails"
		indexes = [
			models.Index(fields=['name','symbol','status'])
		]



class TokenInformation(Auditable):
	name = models.CharField(max_length=50,verbose_name='Name')
	percentage = models.CharField(max_length=50,verbose_name='Percentage')
	colour= models.CharField(max_length=50,verbose_name='Colour',blank=True,null=True)
	content = models.TextField(help_text='Content',verbose_name='Content',blank=True,null=True)
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')
	def __str__(self):
		return "%s" % self.name

	class Meta:
		db_table='kGR7rx1syW59TxKz'
		ordering = ['id']
		verbose_name = "TokenInformation"
		verbose_name_plural ="TokenInformation"
		indexes = [
			models.Index(fields=['name','percentage','status'])
		]

globalexperts/Source/globalexperts/cryptotoken/forms.py
from django.forms import ModelForm
from django import forms


from django.forms import ModelChoiceField

from django.forms import widgets
from betterforms.multiform import MultiModelForm,MultiForm
from django.core.validators import MinValueValidator, MaxValueValidator
from collections import OrderedDict

from django.contrib.auth.models import User,Group

from cryptotoken.models import TokenDetails,RoadMap,CurrencyDetails,TokenInformation


class RoadMapForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={"rows":4, "cols":40}),required=False)
    class Meta:
        model= RoadMap
        fields=['title','years','content','status']
        exclude=['created_on','modified_on','created_by','modified_by' ]


class TokenDetailsForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={"rows":4, "cols":40}),required=False)
    class Meta:
        model= TokenDetails
        fields=['name','symbol','platform','supply','teamwallet','presupply','liquidtypool','token_burn','presaleprice','pancakeswap','liquidity_lock','content','status']
        exclude=['created_on','modified_on','created_by','modified_by' ]

class CurrencyDetailsForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={"rows":4, "cols":40}),required=False)
    class Meta:
        model= CurrencyDetails
        fields=[
        'name',
        'symbol',
        #'platform',
        #'supply',
        # 'reward_distributed',
        # 'charity',
        # 'marketing',
        # 'teamwallet',
        # 'teamwallet_duration',
        # 'presupply',
        # 'liquidtypool',
        # 'presaleprice',
        # 'pancakeswap',
        # 'token_burn',
        # 'blackholeaddress',
        # 'liquiditylock',
        'attachments',
        'timerdate',
        'content'
        ]
        exclude=['created_on','modified_on','created_by','modified_by','status' ]

class TokenInformationForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={"rows":4, "cols":40}),required=False)
    class Meta:
        model= TokenInformation
        fields=['name','percentage','colour','content','status']
        exclude=['created_on','modified_on','created_by','modified_by','status' ]

globalexperts/Source/globalexperts/cryptotoken/templates/cryptotoken/generic_form.html
{% extends 'default_theme/base/__base.html' %}
{% load staticfiles %} 

{% load form_custom %}


{% block Style_sheets %}

{{ subadmin_formset.media.css }}

{% endblock Style_sheets %}

{% load widget_tweaks %}

 {% block Content_Area %}
   
    <section class="content">
    
     
   	 <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="box-title">{{ Title}}</h3>
          <div class="box-tools pull-right">
            {% comment %}
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
            {% endcomment %}
          </div>
        </div>
        {% if messages %}
     {% for message in messages %}
     <div class="alert {{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
         
         <form role="form" action="" method='post' enctype="multipart/form-data" novalidate ="novalidate">
             {% csrf_token %} 
             {{ form.media }}
        
        <div class="box-body">
          <div class="row">
            <div class="col-md-6">
              
             

               {% for ind_form in form %}   
                <div class="form-group">
                  <label >{{ind_form.label}}
                    {% if ind_form|req_label  %} <span class="text-danger"> * </span>{% endif %}
                  </label>
                    {%render_field ind_form class+="form-control" placeholder=ind_form.label %}
                    {% if ind_form.errors %}
                    {% for error in ind_form.errors %}
                     <span class="text-danger">* {{ error|escape }} </span>
                    {% endfor %}
                  {% endif %}
                   
                </div>
               {% endfor %}  
                  
            
            </div>
          
            <div class="col-md-6">
             
          
            </div>
          </div>
          
         <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                  &nbsp;&nbsp;
                <a href="{% url Btn_url %}" class="btn btn-primary">Back</a>
         </div>
          </form>
      </div>

    </section>

 {% endblock Content_Area %}

 {% block Java_Scripts %}

<script type="text/javascript">
    $("#id_timerdate").datetimepicker({format: 'yyyy-mm-dd hh:ii'});
</script>            
 {% endblock %}

globalexperts/Source/globalexperts/cryptotoken/templates/cryptotoken/generic_list.html
{% extends 'default_theme/base/__base.html' %}
{% load staticfiles %} 

{% load form_custom %}

{% block Style_sheets %}


{% endblock Style_sheets %}

 {% load render_table from django_tables2 %}

 {% block Content_Area %}
    
    <section class="content">
  
     
   	 <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="box-title">{{ Title}}</h3>

          <div class="box-tools pull-right">
           
          </div>
        </div>
     {% if messages %}
     {% for message in messages %}
     <div class="alert {{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    
   
     <div class="box">
            <div class="box-header">
              <h3 class="box-title"></h3>
              <div class="box-tools pull-right">                         
                        </div>
            </div>
            <div class="table-responsive">

           
            <div class="box-body">
               {% render_table table %} 
            </div>
            </div>
            
          </div>
        
      </div>

    </section>
   

 {% endblock Content_Area %}

 {% block Java_Scripts %}
 

 {% endblock %}

globalexperts/Source/globalexperts/cryptotoken/templates/cryptotoken/generic_list_add.html
{% extends 'default_theme/base/__base.html' %}
{% load staticfiles %} 

{% load form_custom %}

{% block Style_sheets %}


{% endblock Style_sheets %}

 {% load render_table from django_tables2 %}

 {% block Content_Area %}
  
    <section class="content">
    
     
   	 <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="box-title">{{ Title}}</h3>

          <div class="box-tools pull-right">
           
          </div>
        </div>
     {% if messages %}
     {% for message in messages %}
     <div class="alert {{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
   
   
     <div class="box">
            <div class="box-header">
              <h3 class="box-title"></h3>
              <div class="box-tools pull-right">   
                  <a href="{% url Btn_url %}" class="btn btn-warning">{{add_title}}    </a>

                        </div>
            </div>
            <div class="table-responsive">
            
            <div class="box-body">
               {% render_table table %} 

            </div>
           
            </div>
          </div>
        
      </div>

    </section>
   

 {% endblock Content_Area %}

 {% block Java_Scripts %}
 

 {% endblock %}

globalexperts/Source/globalexperts/cryptotoken/templates/cryptotoken/menu.html

<li>
      <a  href="/token/currencylist/"><i class="fa fa-exchange"></i> <span>
         Token Settings
      </span> </a>
</li>
{% comment %}
<li>
      <a  href="{% url 'cryptotoken:tokenlist' %}"><i class="fa fa-exchange"></i> <span>
         Token List
      </span> </a>
</li>

{% endcomment %}
<li>
      <a  href="{% url 'cryptotoken:roadmaplist' %}"><i class="fa fa-road"></i> <span>
          Manage RoadMap 
      </span> </a>
</li>






globalexperts/Source/globalexperts/cryptotoken/templates/cryptotoken/roadmap_detail.html
{% extends 'default_theme/base/__base.html' %}
{% load staticfiles %} 

{% load form_custom %}


{% block Style_sheets %}
{{ subadmin_formset.media.css }}
{% endblock Style_sheets %}
{% load widget_tweaks %}

 {% block Content_Area %}
   
    <section class="content">
    
     
   	 <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="box-title">{{ Title}}</h3>
          <div class="box-tools pull-right">
            {% comment %}
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
            {% endcomment %}
          </div>
        </div>
        {% if messages %}
     {% for message in messages %}
     <div class="alert {{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
         
         <form role="form" action="" method='post' enctype="multipart/form-data" novalidate ="novalidate">
             {% csrf_token %} 
             {{ form.media }}
        
        <div class="box-body">
          <div class="row">
            <div class="col-md-6">
              
           
                <div class="form-group">
                  <label >
                        Title : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {{roadmapdetail.title}}
                </div>
              <div class="form-group">
                  <label >
                        Years : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                    {{roadmapdetail.years}}
                </div>
                {% if roadmapdetail.content %}
                <div class="form-group">
                  <label >
                        Content : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {{roadmapdetail.content}}
                </div>
                {% else %}
                <div class="form-group">
                  <label >
                        Content : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                  --
                </div>
                {% endif %}

                <div class="form-group">
                  <label >
                        Status : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {{roadmapdetail.get_status_display}}
                </div>
                  
            
            </div>
           
            <div class="col-md-6">
             
         
            </div>
          </div>
          
         <div class="box-footer">

                 <a href="{% url Btn_url %}" class="btn btn-primary">Back</a>
         </div>
          </form>
      </div>

    </section>
   




 {% endblock Content_Area %}

 {% block Java_Scripts %}

 {% endblock %}

globalexperts/Source/globalexperts/cryptotoken/templates/cryptotoken/tokendetail.html
{% extends 'default_theme/base/__base.html' %}
{% load staticfiles %} 

{% load form_custom %}


{% block Style_sheets %}
{{ subadmin_formset.media.css }}
{% endblock Style_sheets %}
{% load widget_tweaks %}

 {% block Content_Area %}
    
    <section class="content">
    
     
   	 <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="box-title">{{ Title}}</h3>
          <div class="box-tools pull-right">
            {% comment %}
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
            {% endcomment %}
          </div>
        </div>
        {% if messages %}
     {% for message in messages %}
     <div class="alert {{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
        
         <form role="form" action="" method='post' enctype="multipart/form-data" novalidate ="novalidate">
             {% csrf_token %} 
             {{ form.media }}
        
        <div class="box-body">
          <div class="row">
            <div class="col-md-6">
              
              
                <div class="form-group">
                  <label >
                        Name : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {{roadmapdetail.name}}
                </div>
              <div class="form-group">
                  <label >
                        Percentage : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                    {{roadmapdetail.percentage}} %
                </div>
                <div class="form-group">
                  <label >
                        Colour : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                  {% if roadmapdetail.colour %}
                    {{roadmapdetail.colour}}
                  {% else %}
                  --
                  {% endif%}
                </div>
                 
                {% if roadmapdetail.content != '' and roadmapdetail.content != None %}
                <div class="form-group">
                  <label >
                        Content : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {{roadmapdetail.content}}
                </div>
                {% else %}
                <div class="form-group">
                  <label >
                        Content : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                  --
                </div>
                {% endif %}
                <div class="form-group">
                  <label >
                        Status : 
                  </label>
                 &nbsp;&nbsp; &nbsp;&nbsp;
                   {{roadmapdetail.get_status_display}}
                </div>
            
            </div>
           
            <div class="col-md-6">
             
           
            </div>
          </div>
         
         <div class="box-footer">

                 <a href="{% url Btn_url %}" class="btn btn-primary">Back</a>
         </div>
          </form>
      </div>

    </section>
    




 {% endblock Content_Area %}

 {% block Java_Scripts %}

 {% endblock %}