globalexperts/Source/globalexperts/globalexperts/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from trade_admin_auth.views import adminlogin
from trade_auth.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^global/',include("trade_auth.urls" ,namespace="trade_auth")),
    re_path(r'^tradeadmin/',include("trade_admin_auth.urls" ,namespace="trade_admin_auth")),
    re_path(r'^trademaster/',include("trade_master.urls" ,namespace="trade_master")),
    re_path(r'^token/',include("cryptotoken.urls" ,namespace="cryptotoken")),
    re_path(r'^support/',include("support.urls" ,namespace="support")),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    re_path('LELPMDfDsmez0ksi', adminlogin, name='adminlogin'),
    re_path('', home, name='home'),
]

globalexperts/Source/globalexperts/support/urls.py
from django.urls import include, path,re_path
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView
app_name = 'support'

loginurl='/W8n9cQU3MAh1mjhT/'

from . import views
from .views import AddSupportCategory,ListSupportCategory,UpdateSupportCategory
from .views import  ListSupportTicket,UpdateSupportTicket,DetailSupportticket,AddNewsletter,ListNewsletter,DetailNewsletter
from .views import ListSubscribeUserAdmin,DeleteSubscribeuser,AddSupportView
from django.views.decorators.csrf import csrf_exempt
urlpatterns = [

	 

	
	re_path(r'^updatesupportcategory/(?P<pk>[-\w]+)/$', login_required(UpdateSupportCategory.as_view(),login_url=loginurl), name='updatesupportcategory'),
	re_path(r'^supportcategorylist/$', login_required(ListSupportCategory.as_view(),login_url=loginurl), name='supportcategorylist'), 
	re_path(r'^addsupportcategory/$', login_required(AddSupportCategory.as_view(),login_url=loginurl), name='addsupportcategory'),
	
	re_path(r'^updatesupportticket/(?P<pk>[-\w]+)/$', login_required(UpdateSupportCategory.as_view(),login_url=loginurl), name='updatesupportticket'),
	re_path(r'^ticketsupportlist/$', login_required(ListSupportTicket.as_view(),login_url=loginurl), name='ticketsupportlist'), 
	re_path(r'^detail_supportticket/(?P<supportid>[-\w]+)/$', login_required(views.supportreply_view,login_url=loginurl), name='detail_supportticket'),

	re_path(r'^addnewsletter/$', login_required(AddNewsletter.as_view(),login_url=loginurl), name='addnewsletter'),
	re_path(r'^listnewsletter/$', login_required(ListNewsletter.as_view(),login_url=loginurl), name='listnewsletter'),
	re_path(r'^newsletterdetail/(?P<pk>[-\w]+)/$', login_required(DetailNewsletter.as_view(),login_url=loginurl), name='newsletterdetail'),

	re_path(r'^newsletter_add/$', login_required(views.newsletter_add,login_url=loginurl), name='newsletter_add'),
	re_path(r'^subscribedetail/(?P<pk>[-\w]+)/$', login_required(DeleteSubscribeuser.as_view(),login_url=loginurl), name='subscribedetail'),
	re_path(r'^subscribe_newsletter_add/$', views.subscribeuser, name='subscribe_newsletter_add'),

	re_path(r'^subscribelist/$', login_required(ListSubscribeUserAdmin.as_view(),login_url=loginurl), name='subscribelist'),
	re_path(r'^getuserlist_ajax', csrf_exempt(views.getuserlist_ajax), name='getuserlist_ajax'),

	re_path(r'^supportticket/$', login_required(AddSupportView.as_view()), name='supportticket'), 
	re_path(r'^tradeuser_supportticket/(?P<supportid>[-\w]+)/$', login_required(views.tradeusersupportreply_view), name='tradeuser_supportticket'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

globalexperts/Source/globalexperts/trade_auth/urls.py
from django.urls import include, path,re_path
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView
from django.views.decorators.csrf import csrf_exempt
app_name = 'trade_auth'

from . import views

loginurl='/LELPMDfDsmez0ksi/'


urlpatterns = [

	re_path('aboutus', views.aboutus, name='aboutus'),
	re_path('whitepaper', views.whitepaper, name='whitepaper'),
	re_path('contactus', views.contactus, name='contactus'),
	re_path('buytoken', views.buytoken, name='buytoken'),
	re_path('ourteam', views.ourteam, name='ourteam'),
	re_path('faq', views.faq, name='faq'),
	re_path('privacy', views.privacy, name='privacy'),
	re_path('terms', views.terms, name='terms'),
	re_path('roadmap', views.roadmap, name='roadmap'),
	re_path('offline', views.offline_view, name='offline_view'),
	re_path('comingsoon', views.comingsoon_view, name='comingsoon'),
	re_path('walletdetails', views.walletdetails, name='walletdetails'),
	re_path('disconnectwallet', views.disconnectwallet, name='disconnectwallet'),
	re_path(r'^connectmetamask', csrf_exempt(views.connection_wallet), name='connectmetamask'),
	path('bloginfo/<int:id>/',views.info_blog,name='blogdetail'),
	re_path('blog', views.blog_list, name='blog'),
	path('markettingvideo/',views.video_list,name='markettingvideo'),
	
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

globalexperts/Source/globalexperts/company/models.py
from django.db import models
from django.core.validators import RegexValidator
from datetime import date
from django.urls import reverse
import os


View_Type = (
                (0,'Live'),
                (1,'Under Maintenance'),

    )

Comming_Soon = (
                (0,'Disable'),
                (1,'Enable'),

    )


class Company(models.Model):
    name = models.CharField(max_length=50,default='Company',verbose_name='Site Name')
    caption = models.CharField(max_length=60,default='',verbose_name='Site Caption',blank=True,null=True)
    director = models.CharField(max_length=60,default='',verbose_name='Director',blank=True,null=True)
    
    reg_info = models.CharField(max_length=60,default='',verbose_name='Site Registration Info',blank=True,null=True)
    
    
   
    address1=models.CharField(max_length=200,verbose_name='Contact Address')
    city = models.CharField(max_length=50,verbose_name='City',blank=True,null=True)
    state = models.CharField(max_length=50,verbose_name='State',blank=True,null=True)
    country = models.CharField(max_length=50,verbose_name='Country',blank=True,null=True)
    postcode = models.CharField(max_length=10,verbose_name='Pin Code',blank=True,null=True)
    
    
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 13 digits allowed.")
    phone1 = models.CharField(max_length=13,help_text='Phone number Format : 0xxxxxxxxxx',verbose_name='Phone Number',blank=True,null=True)
    website = models.CharField(max_length=200,blank=True,null=True)
    email = models.EmailField(max_length=60,blank=True,null=True)
    
    company_logo = models.ImageField(upload_to='logo',verbose_name='Site Logo',blank=True,null=True)
    company_fav = models.ImageField(upload_to='favicons',verbose_name='Site Favicon',blank=True,null=True)
    copy_right =  models.CharField(max_length=200,verbose_name='Copy Rights',blank=True,null=True)
    admin_redirect = models.CharField(max_length=100,verbose_name='Admin Redirect',blank=True,null=True)
    trade_percentage = models.DecimalField(max_digits=16,decimal_places=8,default='0.00000000',verbose_name='Trade Percentage')
    
    gplus = models.CharField(max_length=200,verbose_name='Youtube',blank=True,null=True)
    fb = models.CharField(max_length=200,verbose_name='Facebook',blank=True,null=True)
    twitter = models.CharField(max_length=200,verbose_name='Twitter',blank=True,null=True)
    linkedin = models.CharField(max_length=200,verbose_name='linkedin',blank=True,null=True) 
    instagram =  models.CharField(max_length=200,verbose_name='Instagram',blank=True,null=True)
    social1 =  models.CharField(max_length=200,verbose_name='Reddit',blank=True,null=True)
    social2 =  models.CharField(max_length=200,verbose_name='Discord',blank=True,null=True)
    social3 =  models.CharField(max_length=200,verbose_name='WeChat',blank=True,null=True)
    company_video = models.FileField(upload_to='videofiles',verbose_name='Site Video',blank=True,null=True)
    created_on = models.DateTimeField(auto_now_add = True)
    modified_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    @property
    def companyimage_name(self):
        return  os.path.basename(self.company_logo.path) if self.company_logo else ''

    @property
    def companyfav_name(self):
        return  os.path.basename(self.company_fav.path) if self.company_fav else ''

    class Meta:
        verbose_name = "Company"
        verbose_name_plural = "Companies"
        db_table='Qy3Lp6BUavODzKxC'

class Company_Branches(models.Model):
    name = models.CharField(max_length=50,default='Branch',verbose_name='Branch Name')
    company_name=models.ForeignKey(Company,related_name='branches',on_delete=models.CASCADE)
    
    address1=models.CharField(max_length=100,verbose_name='Contact Address')
    city = models.CharField(max_length=50,verbose_name='City',blank=True,null=True)
    state = models.CharField(max_length=50,verbose_name='State',blank=True,null=True)
    country = models.CharField(max_length=50,verbose_name='Country',blank=True,null=True)
    postcode = models.CharField(max_length=10,verbose_name='Pin Code',blank=True,null=True)
    
    
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 13 digits allowed.")
    phone1 = models.CharField(validators=[phone_regex],max_length=13,help_text='Phone number Format : 0xxxxxxxxxx',verbose_name='Phone Number',blank=True,null=True)
    website = models.CharField(max_length=200,blank=True,null=True)
    email = models.EmailField(max_length=60,blank=True,null=True)
    
    created_on = models.DateTimeField(auto_now_add = True)
    modified_on = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Branch"
        verbose_name_plural = "Branches"
        db_table='SGSEeKuePkYIl06b'

class Company_Settings(models.Model):
    company_settings_name=models.OneToOneField(Company,related_name='company_settings',on_delete=models.CASCADE)
    
    site_maintenance_status= models.IntegerField(choices=View_Type,default=1,verbose_name='Site Maintenance')
    site_maintenance =models.TextField(blank=True,null=True,verbose_name='Coming Soon Message')
    new_coin_status =  models.IntegerField(choices=Comming_Soon,default=0,verbose_name='Coming Soon')
    fees_amount =  models.DecimalField(max_digits=16,decimal_places=8,default='0.00000000',verbose_name='Fee Amount')
    free_bonus_status= models.IntegerField(choices=View_Type,default=1,verbose_name='Bonus Provide Status')
    bonus_amount =  models.DecimalField(max_digits=16,decimal_places=8,default='0.00000000',verbose_name='Bonus Amount')
    free_days = models.CharField(max_length=10,default='Free days',blank=True,null=True)
    margin_percentage =  models.DecimalField(max_digits=16,decimal_places=8,default='0.00000000',verbose_name='Margin Percentage')
    lending_percentage = models.DecimalField(max_digits=16,decimal_places=8,default='0.00000000',verbose_name='Lending Percentage')
    base_price_percenatge = models.DecimalField(max_digits=16,decimal_places=8,default='0.00000000',verbose_name='Base Price Percentage')
    depositurl =  models.CharField(max_length=50,verbose_name='Token Explore Url',blank=True,null=True)
    withdrawurl =  models.CharField(max_length=50,verbose_name='Marketing Video Url',blank=True,null=True)
    coinmarket =  models.CharField(max_length=50,verbose_name='CoinMarket Cap Url',blank=True,null=True)
    coingecko =  models.CharField(max_length=50,verbose_name='CoinGecko Cap Url',blank=True,null=True)
    adminipaddress =  models.CharField(max_length=50,verbose_name='Admin IP Address',blank=True,null=True)

    
    def __int__self(self):
        return self.id

    class Meta:
        verbose_name = "CompanySetting"
        verbose_name_plural = "CompanySetting"
        db_table='tt1PHI2VMhaXFIlt'

class CompanyBranchMixing(models.Model):
    company_id=models.ForeignKey(Company,verbose_name='Company Name',on_delete=models.CASCADE)
    branch_id=models.ForeignKey(Company_Branches,verbose_name='Branch Name',on_delete=models.CASCADE)
    
    class Meta:
        abstract =True

globalexperts/Source/globalexperts/support/models.py
from django.db import models
from django.conf import settings


from datetime import date
from django.contrib.auth.models import User,Group
from django.core.validators import RegexValidator
from auditable.models import Auditable

from django.urls import reverse
import os
from django.db.models import Q
from django.db.models import Count, Min, Sum, Avg ,F,DecimalField
from decimal import Decimal
import time

General_Status = (
					(0,'Active'),
					(1,'Inactive'),
					(2,'Cancel'),
	)
TICKET_Status = (
					(0,'Open'),
					(1,'Processing'),
					(2,'Closed'),
	)

Newsleter_Status = (
					(0,'All User'),
					(1,'Registered User'),
					(2,'Subscriber User'),
					(3,'Specific User'),
	)

class SupportCategory(Auditable):
	
	name = models.CharField(max_length=50,verbose_name='Category Name')
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')

	def __str__(self):
		return self.name
	class Meta:
		verbose_name='SupportCategory'
		db_table='Ww7tRv26SA7LAiQF'

class SupportTicket(Auditable):
	user = models.ForeignKey(User,related_name ='support_user_profile',on_delete=models.CASCADE)
	category = models.ForeignKey(SupportCategory,related_name ='support_categorylist',on_delete=models.CASCADE)
	subject = models.CharField(max_length=150,verbose_name='Subject')
	message = models.TextField(help_text='Message',verbose_name='Message',blank=True,null=True)
	attachment=models.ImageField(upload_to='usersupport',verbose_name='Attachements',blank=True,null=True)
	status=models.IntegerField(choices=TICKET_Status,default=0,verbose_name='Status')

	def __int__self(self):
		return id		
	class Meta:
		verbose_name='SupportTicket'
		db_table='TH3qkdA9J3URDVHw'
class SupportTicketDetails(Auditable):
	user = models.ForeignKey(User,related_name ='supportdetail_user_profile',on_delete=models.CASCADE)
	ticket = models.ForeignKey(SupportTicket,related_name ='support_ticketlist',on_delete=models.CASCADE)
	message = models.TextField(help_text='Message',verbose_name='Reply')
	attachment=models.ImageField(upload_to='usersupportdetail',verbose_name='Attachements',blank=True,null=True)
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')

	def __int__self(self):
		return id		
	class Meta:
		verbose_name='SupportTicketDetails'
		db_table='MBA4H1rKHZhDfggS'


class SubscribeUser(models.Model):
	user = models.ForeignKey(User,related_name ='subscribe_user_profile',on_delete=models.CASCADE)
	created_on = models.DateTimeField(auto_now_add = True)
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')

	def __int__self(self):
		return id	
	class Meta:
		verbose_name='SubscribeUser'
		db_table='qdGChrivvbABICCF'	


class Newsletter(Auditable):
	user = models.ManyToManyField(User,related_name ='newsleter_user_profile')
	category = models.IntegerField(choices=Newsleter_Status,default=0,verbose_name='Type')
	subject = models.CharField(max_length=150,verbose_name='Subject')
	message = models.TextField(help_text='Message',verbose_name='Message',blank=True,null=True)
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')

	def __int__self(self):
		return id		
	class Meta:
		verbose_name='Newsletter'
		db_table='DbNwYgfcQ4osKvrl'	

class NewsletterSubscribeUser(models.Model):
	email = models.CharField(max_length=100,verbose_name='Email')
	created_on = models.DateTimeField(auto_now_add = True)
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')

	def __int__self(self):
		return id
	class Meta:
		verbose_name='NewsletterSubscribeUser'
		db_table='0CiKyhb05gCOp4mB'	

globalexperts/Source/globalexperts/trade_auth/forms.py
from django.forms import ModelForm
from django import forms


from django.forms import ModelChoiceField

from django.forms import widgets
from django.core.exceptions import ValidationError

from django.contrib.auth.models import User,Group
from company.models import Company,Company_Settings

from trade_admin_auth.models import AdminUser_Profile,User_Kyc_Verification
from trade_admin_auth.models import KYC_List
from betterforms.multiform import MultiModelForm,MultiForm
from django.core.validators import MinValueValidator, MaxValueValidator

from django.contrib.auth.forms import UserCreationForm,PasswordResetForm,PasswordChangeForm
from locations.models import Country,State,Cities
from django.db.models import Q,F,Func,Value

from trade_master.models import Contactus

class Contactform(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(attrs={'rows': 4, 'cols': 40}),required = True)
    class Meta:
        model= Contactus
        fields='__all__'
        exclude=['created_on','modified_on','reply','status','read_status',]


    

globalexperts/Source/globalexperts/trade_auth/templates/trade_auth/aboutus.html
{% extends 'default_theme/front/__staticbase.html' %}
{% load staticfiles %} 
{% block Style_sheets %}
{% endblock Style_sheets %}
{% load widget_tweaks %}

{% block Content_Area %}
 <div class="howto-buy-bbf-section">
            <div class="container">
               <h3 class="section_big_heading width_half">{{aboutuspage.title}}</h3>
               <div class="row justify-content-center">
                  <div class="col-xs-12 col-sm-6 col-md-6">
                     <div class="contact-l aos-init aos-animate" data-aos="flip-right">
                        {{aboutuspage.content|safe}}
                     </div>
                  </div>
                  <div class="col-xs-12 col-sm-6 col-md-6">
                     <div class="privacy_sec_img aos-init aos-animate mt-3" data-aos="flip-right">
                        <img src="{% static "frontend_assets/images/about.png"%}" class="img-fluid">
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="howto-buy-bbf-section">
            <div class="container">
               <div class="row justify-content-center burn_sec">
                  <div class="col-xs-12 col-sm-4 col-md-4">
                     <div class="howto-buy-bbf-m" data-aos="flip-right">
                        <h2>{{tokenvalue.content|safe}}</h2>
                        <h5>{{tokenvalue.title}}</h5>
                     </div>
                  </div>
                  <div class="col-xs-12 col-sm-4 col-md-4">
                     <div class="howto-buy-bbf-m buy-left-border" data-aos="flip-right">
                        <h2>{{tokenholder.content|safe}} </h2>
                        <h5>{{tokenholder.title}}</h5>
                     </div>
                  </div>
                  <div class="col-xs-12 col-sm-4 col-md-4">
                     <div class="howto-buy-bbf-m buy-left-border" data-aos="flip-right">
                        <h2>{{tokenliquidity.content|safe}}</h2>
                        <h5>{{tokenliquidity.title}}</h5>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="container">
            <div class="row">
               <div class="col-md-4 mb-2 pl-0">
                  <div class="howto-buy-bbf-m aos-init aos-animate about_clr" data-aos="flip-right">
                     <img src="{% static "frontend_assets/images/a1.png"%}" class="img-fluid">
                     <h5 class="mt-3">{{aboutuscontent1.title}}</h5>
                     <p>
                      {{aboutuscontent1.content|safe}}
                     </p>
                  </div>
               </div>
               <div class="col-md-4 mb-2 pl-0 pr-0">
                  <div class="howto-buy-bbf-m aos-init aos-animate about_clr" data-aos="flip-right">
                     <img src="{% static "frontend_assets/images/a2.png"%}" class="img-fluid">
                     <h5 class="mt-3">{{aboutuscontent2.title}}</h5>
                     <p>
                       {{aboutuscontent2.content|safe}}
                     </p>
                  </div>
               </div>
               <div class="col-md-4 mb-2 pr-0 pr-0">
                  <div class="howto-buy-bbf-m aos-init aos-animate about_clr" data-aos="flip-right">
                     <img src="{% static "frontend_assets/images/a3.png"%}" class="img-fluid">
                     <h5 class="mt-3">{{aboutuscontent3.title}}</h5>
                     <p> {{aboutuscontent3.content|safe}}
                     </p>
                  </div>
               </div>
            </div>
         </div>
{% endblock Content_Area %}

{% block Java_Scripts %}
{% endblock %}

globalexperts/Source/globalexperts/trade_auth/templates/trade_auth/blog_detail.html
{% extends 'default_theme/front/__staticbase.html' %}
{% load staticfiles %} 
{% block Style_sheets %}
{% endblock Style_sheets %}
{% load widget_tweaks %}
{% block Content_Area %}     
 <main>
      
         <div class="how-all-start-section">
            <div class="container">
             
             
               <div class="row justify-content-center">
                  <div class="col-xs-12 col-sm-12 col-md-12">
                     <div class="bbf-whitepaper-m mt-5">
                        <h1 class="section_big_heading text-center width_half">Blog Detail</h1>
                        <div> </div>
                     </div>
                  </div>
                 
                  
               </div>
               <div class="row aos-init aos-animate" data-aos="zoom-in">
                  <div class="col-xs-12 col-sm-12 col-md-12">
                     <div class="mt-3">
                        {% if  blog.blogimage.url != None %}
                        <img src="{{ blog.blogimage.url }}" class="img-fluid">
                        {% else %}
                        <img src="#" class="img-fluid">
                        {% endif %} 
                         <h5 class="mt-4">{{ blog.blogtitle }}</h5>
                          {{ blog.blogcontent|safe }}
                     </div>
                    
                  </div>
             
              

                  </div>
             
                  
                 
                  
               </div>
            </div>
         </div>
      
         </div>
       
      </main>
{% endblock Content_Area %}
{% block Java_Scripts %}
{% endblock %}
   

globalexperts/Source/globalexperts/trade_auth/templates/trade_auth/contact.html
{% extends 'default_theme/front/__staticbase.html' %}
{% load staticfiles %} 
{% block Style_sheets %}
{% endblock Style_sheets %}
{% load widget_tweaks %}

{% block Content_Area %}

<div class="howto-buy-bbf-section">
       <div class="container">
        <div class="row justify-content-center">
        <div class="col-xs-12 col-sm-6 col-md-6">
          <div class="contact-l aos-init aos-animate" data-aos="flip-right">
            <div>
              {% comment %}
               <h1 class="section_big_heading width_half">Contact Us</h1>
              
              <h6 class="text-yellow">Get a quote</h6>
              <p class="text-white padd-bot-10">If you are interested or have any questions,send us message.</p>
              {% endcomment %}
             <div class="con_left_sec">
             <p>Email Social: Social@dxbpay.cc</p>
             <p>Email Admin: Admin@dxbpay.cc</p>
             <p>Telegram : <a href="https://t.me/DXBPay">https://t.me/DXBPay</i></a></p>
           </div>

          <ul class="footer-social-col mt-4">
             {% comment %}
            <li><a href="{{companyqs.fb}}" target="_blank" class="footer-links"><i class="fab fa-facebook"></i></a></li>
            
            <li><a href="{{companyqs.twitter}}" target="_blank" class="footer-links"><i class="fab fa-twitter"></i></a></li>
           
            <li><a href="{{companyqs.gplus}}" target="_blank"  class="footer-links"><i class="fab fa-youtube"></i></a></li>
            {% endcomment %}
            </ul>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6">
          <form class="contact_form" method="POST" action="/global/contactus/" >
            {% csrf_token %}
            {{ form.media }}
          <div class="contact-r aos-init aos-animate contact_bg" data-aos="flip-right">
            <div class="contact-sec-main d-flex">
              <div class="contact-sec-1">
                <input type="text" name="name" id="id_name" value="" required placeholder="Enter Name">
              </div>
              <div class="contact-sec-2">
                <input type="email" name="email" id="id_email" required value="" placeholder="Enter e-mail address">
              </div>
            </div>
            <div class="contact-sec-main d-flex">
            <div class="contact-sec-1">
              {% comment %}
            <select class="form-select" aria-label="Default select example">
              <option selected>Select subject</option>
              <option value="1">One</option>
              <option value="2">Two</option>
              <option value="3">Three</option>
            </select>
            {% endcomment %}
            <input type="text" name="subject" value="" id="id_subject" placeholder="Subject" required>
            </div>
            </div>
            <div class="contact-sec-main2">
              <textarea placeholder="Enter message" name="message" id="id_message"required></textarea>
            </div>
            <script src='https://www.google.com/recaptcha/api.js'></script>
             <div class="g-recaptcha" data-sitekey="6LfOCpYbAAAAAL_33CjuKZhX2ZOV_EkliV5YptXd"></div>
            <br/>
            <div class="text-center">
              <button class="btn-primary" name="conatctsubmit" type="submit">Submit</button>
            </div>
          </div>
        </form>
        </div>
        </div>
        </div>
</div>
{% endblock Content_Area %}

{% block Java_Scripts %}
{% endblock %}

globalexperts/Source/globalexperts/trade_auth/templates/trade_auth/home.html
{% extends 'default_theme/front/__base.html' %}
{% load staticfiles %} 
{% block Style_sheets %}
{% endblock Style_sheets %}
{% load widget_tweaks %}

{% block Java_Scripts %}
{% endblock %}

globalexperts/Source/globalexperts/trade_auth/templates/trade_auth/privacy.html
{% extends 'default_theme/front/__staticbase.html' %}
{% load staticfiles %} 
{% block Style_sheets %}
{% endblock Style_sheets %}
{% load widget_tweaks %}

{% block Content_Area %}
<div class="howto-buy-bbf-section">
    <div class="container">


     <h3 class="section_big_heading width_half">{{cms_content.title}}</h3>
     
<div class="row justify-content-center">
        
        <div class="col-xs-12 col-sm-6 col-md-6">
          <div class="contact-l aos-init aos-animate" data-aos="flip-right">
               {{cms_content.content|safe}}
          </div>
        </div>
         <div class="col-xs-12 col-sm-6 col-md-6">
          <div class="privacy_sec_img aos-init aos-animate mt-3" data-aos="flip-right">
      <img src="{% static "frontend_assets/images/privacy.png"%}" class="img-fluid">
          </div>
        </div>


            <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="contact-l aos-init aos-animate" data-aos="flip-right">

            {{cms_content_twores.content|safe}}

          </div>
        </div>
      </div>


  </div>
       </div>
{% endblock Content_Area %}

{% block Java_Scripts %}
{% endblock %}