globalexperts/Source/globalexperts/globalexperts/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from trade_admin_auth.views import adminlogin
from trade_auth.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^global/',include("trade_auth.urls" ,namespace="trade_auth")),
    re_path(r'^tradeadmin/',include("trade_admin_auth.urls" ,namespace="trade_admin_auth")),
    re_path(r'^trademaster/',include("trade_master.urls" ,namespace="trade_master")),
    re_path(r'^token/',include("cryptotoken.urls" ,namespace="cryptotoken")),
    re_path(r'^support/',include("support.urls" ,namespace="support")),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    re_path('LELPMDfDsmez0ksi', adminlogin, name='adminlogin'),
    re_path('', home, name='home'),
]

globalexperts/Source/globalexperts/support/urls.py
from django.urls import include, path,re_path
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView
app_name = 'support'

loginurl='/W8n9cQU3MAh1mjhT/'

from . import views
from .views import AddSupportCategory,ListSupportCategory,UpdateSupportCategory
from .views import  ListSupportTicket,UpdateSupportTicket,DetailSupportticket,AddNewsletter,ListNewsletter,DetailNewsletter
from .views import ListSubscribeUserAdmin,DeleteSubscribeuser,AddSupportView
from django.views.decorators.csrf import csrf_exempt
urlpatterns = [

	 

	
	re_path(r'^updatesupportcategory/(?P<pk>[-\w]+)/$', login_required(UpdateSupportCategory.as_view(),login_url=loginurl), name='updatesupportcategory'),
	re_path(r'^supportcategorylist/$', login_required(ListSupportCategory.as_view(),login_url=loginurl), name='supportcategorylist'), 
	re_path(r'^addsupportcategory/$', login_required(AddSupportCategory.as_view(),login_url=loginurl), name='addsupportcategory'),
	
	re_path(r'^updatesupportticket/(?P<pk>[-\w]+)/$', login_required(UpdateSupportCategory.as_view(),login_url=loginurl), name='updatesupportticket'),
	re_path(r'^ticketsupportlist/$', login_required(ListSupportTicket.as_view(),login_url=loginurl), name='ticketsupportlist'), 
	re_path(r'^detail_supportticket/(?P<supportid>[-\w]+)/$', login_required(views.supportreply_view,login_url=loginurl), name='detail_supportticket'),

	re_path(r'^addnewsletter/$', login_required(AddNewsletter.as_view(),login_url=loginurl), name='addnewsletter'),
	re_path(r'^listnewsletter/$', login_required(ListNewsletter.as_view(),login_url=loginurl), name='listnewsletter'),
	re_path(r'^newsletterdetail/(?P<pk>[-\w]+)/$', login_required(DetailNewsletter.as_view(),login_url=loginurl), name='newsletterdetail'),

	re_path(r'^newsletter_add/$', login_required(views.newsletter_add,login_url=loginurl), name='newsletter_add'),
	re_path(r'^subscribedetail/(?P<pk>[-\w]+)/$', login_required(DeleteSubscribeuser.as_view(),login_url=loginurl), name='subscribedetail'),
	re_path(r'^subscribe_newsletter_add/$', views.subscribeuser, name='subscribe_newsletter_add'),

	re_path(r'^subscribelist/$', login_required(ListSubscribeUserAdmin.as_view(),login_url=loginurl), name='subscribelist'),
	re_path(r'^getuserlist_ajax', csrf_exempt(views.getuserlist_ajax), name='getuserlist_ajax'),

	re_path(r'^supportticket/$', login_required(AddSupportView.as_view()), name='supportticket'), 
	re_path(r'^tradeuser_supportticket/(?P<supportid>[-\w]+)/$', login_required(views.tradeusersupportreply_view), name='tradeuser_supportticket'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

globalexperts/Source/globalexperts/support/models.py
from django.db import models
from django.conf import settings


from datetime import date
from django.contrib.auth.models import User,Group
from django.core.validators import RegexValidator
from auditable.models import Auditable

from django.urls import reverse
import os
from django.db.models import Q
from django.db.models import Count, Min, Sum, Avg ,F,DecimalField
from decimal import Decimal
import time

General_Status = (
					(0,'Active'),
					(1,'Inactive'),
					(2,'Cancel'),
	)
TICKET_Status = (
					(0,'Open'),
					(1,'Processing'),
					(2,'Closed'),
	)

Newsleter_Status = (
					(0,'All User'),
					(1,'Registered User'),
					(2,'Subscriber User'),
					(3,'Specific User'),
	)

class SupportCategory(Auditable):
	
	name = models.CharField(max_length=50,verbose_name='Category Name')
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')

	def __str__(self):
		return self.name
	class Meta:
		verbose_name='SupportCategory'
		db_table='Ww7tRv26SA7LAiQF'

class SupportTicket(Auditable):
	user = models.ForeignKey(User,related_name ='support_user_profile',on_delete=models.CASCADE)
	category = models.ForeignKey(SupportCategory,related_name ='support_categorylist',on_delete=models.CASCADE)
	subject = models.CharField(max_length=150,verbose_name='Subject')
	message = models.TextField(help_text='Message',verbose_name='Message',blank=True,null=True)
	attachment=models.ImageField(upload_to='usersupport',verbose_name='Attachements',blank=True,null=True)
	status=models.IntegerField(choices=TICKET_Status,default=0,verbose_name='Status')

	def __int__self(self):
		return id		
	class Meta:
		verbose_name='SupportTicket'
		db_table='TH3qkdA9J3URDVHw'
class SupportTicketDetails(Auditable):
	user = models.ForeignKey(User,related_name ='supportdetail_user_profile',on_delete=models.CASCADE)
	ticket = models.ForeignKey(SupportTicket,related_name ='support_ticketlist',on_delete=models.CASCADE)
	message = models.TextField(help_text='Message',verbose_name='Reply')
	attachment=models.ImageField(upload_to='usersupportdetail',verbose_name='Attachements',blank=True,null=True)
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')

	def __int__self(self):
		return id		
	class Meta:
		verbose_name='SupportTicketDetails'
		db_table='MBA4H1rKHZhDfggS'


class SubscribeUser(models.Model):
	user = models.ForeignKey(User,related_name ='subscribe_user_profile',on_delete=models.CASCADE)
	created_on = models.DateTimeField(auto_now_add = True)
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')

	def __int__self(self):
		return id	
	class Meta:
		verbose_name='SubscribeUser'
		db_table='qdGChrivvbABICCF'	


class Newsletter(Auditable):
	user = models.ManyToManyField(User,related_name ='newsleter_user_profile')
	category = models.IntegerField(choices=Newsleter_Status,default=0,verbose_name='Type')
	subject = models.CharField(max_length=150,verbose_name='Subject')
	message = models.TextField(help_text='Message',verbose_name='Message',blank=True,null=True)
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')

	def __int__self(self):
		return id		
	class Meta:
		verbose_name='Newsletter'
		db_table='DbNwYgfcQ4osKvrl'	

class NewsletterSubscribeUser(models.Model):
	email = models.CharField(max_length=100,verbose_name='Email')
	created_on = models.DateTimeField(auto_now_add = True)
	status=models.IntegerField(choices=General_Status,default=0,verbose_name='Status')

	def __int__self(self):
		return id
	class Meta:
		verbose_name='NewsletterSubscribeUser'
		db_table='0CiKyhb05gCOp4mB'	

globalexperts/Source/globalexperts/support/views.py
from django.shortcuts import render
from django.shortcuts import render,get_list_or_404, get_object_or_404
from django.conf import settings


from django.views.generic.edit import CreateView,UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from django.views.generic import TemplateView,View


from django.http.response import HttpResponseRedirect
from django.http import HttpResponse,Http404
from django.urls import reverse
from django.urls import reverse_lazy
from django.template.context_processors import csrf
from django.shortcuts import redirect
from django.http import JsonResponse

from datetime import date,timedelta
import datetime
import json


from django.db.models import Q,F,Func,Value
from django.db.models import Count, Min,Max, Sum, Avg,DecimalField,DateTimeField,CharField
from django.db.models.expressions import RawSQL
from django.db.models.functions import Cast,TruncSecond,ExtractSecond


from django.db import transaction

from django.contrib import auth
from django.contrib.auth.models import User,Group
from django.contrib import messages
from django.core.mail import send_mail

from trade_perms.mixins import OR_PermissionsRequiredMixin, shared_permission_access, admin_permission_access
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required,user_passes_test
from django.core.exceptions import PermissionDenied
from auditable.views import AuditableMixin
from django.db.models import Subquery
# from trade_auth.views import count_referal_code
from trade_auth.views import CompanyMaintanceRequiredMixin,check_company

from django_ajax.decorators import ajax
from trade_admin_auth.mixins import check_group
from trade_admin_auth.mixins import ManageTicketSupportAdminRequiredMixin,ManageNewsletterAdminRequiredMixin

from django_tables2 import RequestConfig
from support.models import SupportCategory,SupportTicket,Newsletter,SubscribeUser,NewsletterSubscribeUser
from support.models import SupportTicketDetails
from support.forms import SupportCategoryForm,NewsletterForm,SupportTicketForm,SupportTicketDetailAdminForm
from support.forms import SupportTicketDetailForm
from support.tables import SupportCategoryTable,SupportTicketTable,NewsletterTable

from trade_master.models import EmailTemplate

import base64
import re
from Crypto.Cipher import AES

from Crypto.Hash import SHA256
from Crypto.Cipher import AES
import base64, json, math
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template


class AddSupportCategory(ManageTicketSupportAdminRequiredMixin,CreateView):
    model = SupportCategory
    form_class = SupportCategoryForm
    template_name = 'support/generic_form.html'   
    def get_context_data(self, **kwargs):
       context = super(AddSupportCategory, self).get_context_data(**kwargs)
       context['Title'] = 'Add SupportCategory'
       context['activecls']='supportadmin'
       context['Btn_url']='support:supportcategorylist'
       return context

    @transaction.atomic
    def form_valid(self, form):
        
       form.instance.created_on   = datetime.datetime.now()
       form.instance.created_by_id = self.request.user.id
       form.instance.modified_by_id = self.request.user.id
       formsave=form.save()

       messages.add_message(self.request, messages.SUCCESS, 'support category created successfully.')
       return HttpResponseRedirect('/support/supportcategorylist/')

class ListSupportCategory(ManageTicketSupportAdminRequiredMixin,ListView):
    model = SupportCategory
    template_name = 'support/generic_list_add.html'
    def get_queryset(self, **kwargs):
      return SupportCategory.objects.all()
    
    def get_context_data(self,**kwargs):
        context=super(ListSupportCategory, self).get_context_data(**kwargs)
        context['Title'] = 'List SupportCategory '
        content_qs = SupportCategory.objects.all()
        context['content_qs'] =content_qs
        contenttable = SupportCategoryTable(content_qs)
        context['table'] = contenttable
        context['add_title'] ='Add SupportCategory'
        context['Btn_url'] = 'support:addsupportcategory'
        context['activecls']='supportadmin'
        return context   

class UpdateSupportCategory(ManageTicketSupportAdminRequiredMixin,UpdateView):
    model = SupportCategory
    form_class = SupportCategoryForm
    template_name = 'support/generic_form.html'   
    def get_context_data(self, **kwargs):
       context = super(UpdateSupportCategory, self).get_context_data(**kwargs)
       context['Title'] = 'Update SupportCategory'
       context['Btn_url']='support:supportcategorylist'
       context['activecls']='supportadmin'
       return context

    @transaction.atomic
    def form_valid(self, form):
       form.instance.modified_by_id = self.request.user.id
       formsave=form.save()

       messages.add_message(self.request, messages.SUCCESS, 'support category updated successfully.')
       return HttpResponseRedirect('/support/supportcategorylist/')



class ListSupportTicket(ManageTicketSupportAdminRequiredMixin,ListView):
    model = SupportTicket
    template_name = 'support/generic_list.html'
    def get_queryset(self, **kwargs):
      return SupportTicket.objects.all()
    
    def get_context_data(self,**kwargs):
        context=super(ListSupportTicket, self).get_context_data(**kwargs)
        context['Title'] = 'List SupportTickets '
        content_qs = SupportTicket.objects.all()
        context['content_qs'] =content_qs
        contenttable = SupportTicketTable(content_qs)
        context['table'] = contenttable
        context['add_title'] ='Add SupportCategory'
        context['Btn_url'] = 'support:addsupportcategory'
        context['activecls']='supportadmin'
        return context   

class UpdateSupportTicket(ManageTicketSupportAdminRequiredMixin,UpdateView):
    model = SupportTicket
    form_class = SupportCategoryForm
    template_name = 'support/generic_form.html'   
    def get_context_data(self, **kwargs):
       context = super(UpdateSupportTicket, self).get_context_data(**kwargs)
       context['Title'] = 'Update SupportTickets'
       context['activecls']='supportadmin'
       return context

    @transaction.atomic
    def form_valid(self, form):
       form.instance.modified_by_id = self.request.user.id
       formsave=form.save()

       messages.add_message(self.request, messages.SUCCESS, 'support ticket updated successfully.')
       return HttpResponseRedirect('/support/ticketsupportlist/')

class DetailSupportticket(ManageTicketSupportAdminRequiredMixin,DetailView):
    model = SupportTicket 
    template_name = 'support/ticketdetail_detail.html'
    def get_context_data(self, **kwargs):
       context = super(DetailSupportticket, self).get_context_data(**kwargs)
       p_key = int(self.kwargs['pk'])
       staticcontent_qs = SupportTicket.objects.get(id=p_key)
       context['Title'] = 'SupportTicket Detail'
       context['staticcontent_qs']=staticcontent_qs
       context['activecls']='supportadmin'
       
       return context         

class AddNewsletter(ManageNewsletterAdminRequiredMixin,CreateView):
    model = Newsletter
    form_class = NewsletterForm
    template_name = 'support/newsletter.html'   
    def get_context_data(self, **kwargs):
       context = super(AddNewsletter, self).get_context_data(**kwargs)
       context['Title'] = 'Add Newsletter'
       context['userlist'] = User.objects.filter(admin_user_profile__role=2)
       return context

    @transaction.atomic
    def form_valid(self, form):
        
       form.instance.created_on   = datetime.datetime.now()
       form.instance.created_by_id = self.request.user.id
       form.instance.modified_by_id = self.request.user.id
       formsave=form.save()

       messages.add_message(self.request, messages.SUCCESS, 'newsletter created successfully.')
       return HttpResponseRedirect('/support/listnewsletter/')       

class ListNewsletter(ManageNewsletterAdminRequiredMixin,ListView):
    model = Newsletter
    template_name = 'support/generic_list_add.html'
    def get_queryset(self, **kwargs):
      return Newsletter.objects.all()
    
    def get_context_data(self,**kwargs):
        context=super(ListNewsletter, self).get_context_data(**kwargs)
        context['Title'] = 'List Newsletter '
        content_qs = Newsletter.objects.all()
        context['content_qs'] =content_qs
        contenttable = NewsletterTable(content_qs)
        context['table'] = contenttable
        context['add_title'] ='Add Newsletter'
        context['Btn_url'] = 'support:addnewsletter'
        return context

class DetailNewsletter(ManageNewsletterAdminRequiredMixin,DetailView):
    model = Newsletter 
    template_name = 'support/newsletterdetail.html'
    def get_context_data(self, **kwargs):
       context = super(DetailNewsletter, self).get_context_data(**kwargs)
       p_key = int(self.kwargs['pk'])
       staticcontent_qs = Newsletter.objects.get(id=p_key)
       context['Title'] = 'Newsletter Detail'
       context['staticcontent_qs']=staticcontent_qs
       return context                         


class ListSubscribeUserAdmin(ListView):
    model = NewsletterSubscribeUser
    template_name = 'support/subscribeuser_list.html'
    def get_queryset(self, **kwargs):
      return NewsletterSubscribeUser.objects.all().order_by('-id')
    
    def get_context_data(self,**kwargs):
        context=super(ListSubscribeUserAdmin, self).get_context_data(**kwargs)

globalexperts/Source/globalexperts/support/templates/support/menu.html
 {% comment %}
 {% if menu_permissions_ticket == 1 or menu_permissions_ticket == 2 %}
 
<li class=" {% if activecls == 'supportadmin'%} active {% endif %}treeview">
          <a href="#">
            <i class="fa fa-support"></i> <span>Support</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{% url 'support:supportcategorylist' %}"><i class="fa fa-circle-o"></i> Category </a></li>
             <li><a href="{% url 'support:ticketsupportlist' %}"><i class="fa fa-circle-o"></i> Tickets </a></li>
           
          </ul>
        </li>
 {% endif%}
 {% endcomment %}


<li class="{% if activecls == 'newsletteradmin' %} active {% endif %} treeview">
          <a href="#">
            <i class="fa fa-newspaper-o"></i> <span>Manage Newsletter</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{% url 'support:subscribelist' %}"><i class="fa fa-circle-o"></i> Subscribe user list </a></li>
            <li><a href="{% url 'support:newsletter_add' %}"><i class="fa fa-circle-o"></i> Newsletter </a></li>
             
           
          </ul>
        </li>


globalexperts/Source/globalexperts/support/templates/support/newsletter.html
{% extends 'default_theme/base/__base.html' %}
{% load staticfiles %} 

{% load form_custom %}


{% block Style_sheets %}
{{ subadmin_formset.media.css }}

{% endblock Style_sheets %}
{% load widget_tweaks %}

 {% block Content_Area %}
    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
     
   	 <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="box-title">{{ Title}}</h3>
          <div class="box-tools pull-right">
            {% comment %}
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
            {% endcomment %}
          </div>
        </div>
        {% if messages %}
     {% for message in messages %}
     <div class="alert {{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
         <!-- form start -->
         <form role="form" action="" method='post' enctype="multipart/form-data" >
             {% csrf_token %} 
             {{ form.media }}
        <!-- /.box-header -->
        <div class="box-body">
          <div class="row">
            <div class="col-md-8">
              
              <!-- /.form-group -->

              <div class="form-group">
                  <label >Type
                  </label>
               <select name="category" class="form-control currencypair_select" placeholder="Type" id="id_category" required="">
                  <option value="0" selected="">All User</option>
                  {% comment %}
                  <option value="1" >Registered User</option>
                  {% endcomment %}
                  <option value="2">Subscriber User</option>
                 
                  <option value="3">Specific User</option>
                </select>  
            </div>
            <div class="form-group">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>S.No</th>
                  <th>Email Address</th>
                </tr>
                </thead>
                <tbody id='marketprice_rowdata_id'>
                  {%  if userlist %}
                  {% for item in userlist %}
                     <tr>
                      <td><input type="checkbox" name="userlist" value="{{ item.id }}" id='userid_{{ item.id }}'></td>
                      <td>{{item.email }} </td>
                     </tr>
                  {% endfor %}  
                  {% endif %}
                </tbody>
                 
               </table>  
            </div>
         

            <div class="form-group">
                
                  <label >Subject
                  </label>
                   <input type="text"  name="subject" id="idsubject" value="" class="form-control" required> 
            </div>
            <div class="form-group">
                
                  <label >Message
                  </label>
                   <textarea name="message" cols="40" rows="10" class="form-control" placeholder="Message" id="id_message" required></textarea> 
            </div>
            
              <!-- /.form-group -->
            </div>
            <!-- /.col -->
            <div class="col-md-4">
             
            <!-- /.col -->
            </div>
          </div>
           <!-- /.second row -->
        <!-- /.box-body -->
         <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
         </div>
          </form>
      </div>

    </section>
    <!-- /.content -->




 {% endblock Content_Area %}

 {% block Java_Scripts %}
<script type="text/javascript" src="{% static 'django_ajax/js/jquery.ajax.min.js' %}"></script>

 <script>

   $('body').on('change', '.currencypair_select', function(){
        var  user_id = $(this).find(":selected").val();
       var values= {'category':user_id }

        $.ajax({
          url: '/support/getuserlist_ajax/',
          csrfmiddlewaretoken: "{{ csrf_token }}",
          headers: {
                  'Accept': 'application/json',
                  'Content-Type': 'application/json'
                 },
          type: 'post',
          data:JSON.stringify(values),
          success: function(content){ 
          var json_obj = JSON.parse(content.content);
          console.log(json_obj)
          $("#marketprice_rowdata_id").empty();
              
          for (var i = 0; i < json_obj.marketdatalist.length; i++) {
            //console.log(json_obj.marketdatalist[i].vendor_id)

            $('#marketprice_rowdata_id').append("<tr><td><input type='checkbox' name='userlist' value="+ json_obj.marketdatalist[i].id+" id='userid_"+ json_obj.marketdatalist[i].id+"'></td><td>"+json_obj.marketdatalist[i].email+"</td></tr>");

          }
          },

        //complete:function(content){
         
        //setTimeout(fetchdata,5000);
        //}
        });
      });
 </script>
 {% endblock %}

globalexperts/Source/globalexperts/support/templates/support/supportform.html
{% extends 'default_theme/front/__Profilebase.html' %}
{% load staticfiles %}
{% block Style_sheets %}

</style>
{% endblock Style_sheets %}
{% load form_custom %}
{% load widget_tweaks %}
{% block Content_Area %}
<section class="myprofile-section myprofile-section-down">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 col-md-12 col-12">
              <div class="myprofile-page deposit_page">
                <h3 class="text-red dash_m_wallet">
                  <div class="dash_l_wallet">Support</div>
                </h3>
                <form class="green_form supportForm" name="withdrawform" id="idwithdraw" method="POST" action="#" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{ form.media }}
                <div class="row">
                  <div class="col-lg-6 col-md-6 col-12">
                    <div class="row mt-3">
                       <div class="col-lg-12 col-md-12 col-12">
                        <p>Category {% if form.category|req_label  %} <span class="text-danger"> * </span>{% endif %}</p>
                        <select name="category" class="" placeholder=" " required="" id="id_category">
                              {% if userqueryset %}
                               {% for item in userqueryset %}
                                <option value="{{ item.id }}" >{{ item.name }}</option>
                               {% endfor %}
                              {% endif %}
                              </select>  
                       </div>
                    </div>
                    <div class="row mt-3">
                       <div class="col-lg-12 col-md-12 col-12">
                         <p>Subject {% if form.subject|req_label  %} <span class="text-danger"> * </span>{% endif %}</p>
                        {%render_field form.subject class+="" placeholder=' Subject' %}
                            {% if form.subject.errors %}
                            {% for error in form.subject.errors %}
                              <span class="text-danger">* {{ error|escape }} </span>
                            {% endfor %}
                            {% endif %}
                       </div>
                    </div>
                    <div class="row mt-3">
                       <div class="col-lg-12 col-md-12 col-12">
                         <p>Messages{% if form.message|req_label  %} <span class="text-danger"> * </span>{% endif %}</p>
                        {% render_field form.message class+="" placeholder=' Message' %}
                       </div>
                    </div>
                    <div class="row mt-3">
                       <div class="col-lg-12 col-md-12 col-12">
                         <p>Attachments{% if form.attachment|req_label  %} <span class="text-danger"> * </span>{% endif %}</p>
                        {%render_field form.attachment class+="" placeholder='Attachments ' %}
                            {% if form.attachment.errors %}
                            {% for error in form.attachment.errors %}
                              <span class="text-danger">* {{ error|escape }} </span>
                            {% endfor %}
                            {% endif %}
                       </div>
                    </div>
                    <div class="row mt-3">
                      <div class="col-lg-12 col-md-12 col-12 text-right">
                         <button class="addenquiry-btn" type="submit" >SUBMIT </button>
                      </div>
                    </div>
                  </div>
                   <div class="col-lg-6 col-md-6 col-12">
                    <h4 class="text-red dash_m_wallet">
                  <div class="dash_l_wallet">Tickets</div>
                  </h4>
                  <div class="tickets_accordion">
            <div id="accordion_tickets">
              <div class="card">
                <div class="card-header" id="headingOne">
                  <h5 class="mb-0">
                    {% if supportdetail %}
                    {% for item in supportdetail %}
                    <a href="{% url 'support:tradeuser_supportticket' item.id %}" title="Detail" class="btn w-100">
                    <div class="btn ticket_header d-flex align-items-center justify-content-between" data-toggle="collapse" href="#ticket_accordion_1" role="button" aria-expanded="false" aria-controls="collapseExample">
                      <div class="d-inline-flex align-items-center ticketLeft">
                        <div class="ticket_date mr-sm-3">
                          <div class="date_t">{{ item.created_on|date:"d" }}</div>
                          <div class="month_t">{{ item.created_on|date:"b Y" }}</div>
                        </div>
                        <div class="ticket_title mr-auto">
                          <div class="ticket_id">Subject : </div>
                          <div class="ticketdate_equity">{{ item.subject }} </div>
                        </div>
                      </div> 
                      <div class=" d-inline-flex align-items-center ticketRight">
                        <div class="ticket_status mr-2">
                          Status    :    <span>{{ item.get_status_display }}</span>
                        </div>
                        <div class="ticket_arrow">
                          <span><i class="fas fa-angle-down"></i></span>
                        </div>
                       </div> 
                    </div>
                    </a>
                    {% endfor %}
                    {% else %}
                    <div class="btn ticket_header d-sm-flex align-items-center" data-toggle="collapse" href="#ticket_accordion_1" role="button" aria-expanded="false" aria-controls="collapseExample">
                      <div class="ticket_title mr-auto">
                        No records found.
                      </div>
                    </div>
                    {% endif %} 
                  </h5>
                </div>
                
              </div>    
            </div><!--Accordion ends here-->
          </div>
                  </div>
                </div>
              </form>
              </div>
            </div>
          </div>
        </div>
</section>
{% endblock Content_Area %}
{% block Java_Scripts %}
<script type="text/javascript" src="{% static 'django_ajax/js/jquery.ajax.min.js' %}"></script>


{% endblock %}